---
permalink: migrate/migrate_to_ng.html 
sidebar: sidebar 
keywords: migrate 
summary: Ao migrar dados de storage, os back-ends de storage são integrados manualmente usando APIS REST. Ao migrar dados do provedor VASA, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB. 
---
= Migrar para a versão mais recente das ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao migrar dados de storage, os back-ends de storage são integrados manualmente usando APIS REST. Ao migrar dados do provedor VASA, os dados são exportados do banco de dados Derby existente e importados para o banco de dados MongoDB.


NOTE: Recomenda-se migrar a configuração clássica somente se a configuração estiver atendendo somente ao recurso do provedor VASA. Se você tiver recursos como armazenamentos de dados tradicionais/NVMe, replicação do vVol e se o SRA estiver ativado no clássico, não é recomendável migrar a configuração para as ferramentas do ONTAP para o VMware vSphere 10,0.

*Sobre esta tarefa*

A migração é compatível com as ferramentas do ONTAP para as versões do VMware vSphere 9.10D2 e 9.11D4 para a versão 10,0. Para migrar de: * As ferramentas do ONTAP para a versão do VMware vSphere 9,10, primeiro atualize para a versão 9.10D2 e depois migre para a versão 10,0. * As ferramentas do ONTAP para a versão do VMware vSphere 9,11, primeiro atualize para a versão 9.11D4 e depois migre para a versão 10,0.


NOTE: Como um usuário existente, você precisa fazer o backup OVA de 9,10/9,11 antes de atualizar para o patch 9,10D ou 9,11D

*Passos*

. Ative A PORTA Derby 1527 nas ferramentas existentes do ONTAP para VMware vSphere 9.10D2 e 9.11D4. Para ativar a porta, faça login na CLI com o usuário root e execute o seguinte comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implantar as ferramentas OVA para ONTAP para a versão do VMware vSphere 10,0. Consulte link:../deploy/qsg_10.html["Ferramentas ONTAP Início rápido"]
. Adicione o vCenter que você deseja migrar para as ferramentas do ONTAP para a versão do VMware vSphere 10,0. link:../configure/add_vcenter.html["Adicione o vCenter"]Consulte .
. Back-end de storage integrado localmente a partir do plug-in remoto vCenter APIs. link:../configure/onboard_svm.html["Back-end de storage integrado"]Consulte . Adicione armazenamento como escopo local para migração.
. Use a seguinte API para migrar:
+
[listing]
----
/api/v1/vcenters/{vcguid}/migration-jobs

{
  "otv_ip": "10.10.10.10",
  "vasa_provider_credentials": {
    "username": "Administrator",
    "password": "password"
  }
}
----
+
A chamada API acima dá o jobid, que pode ser usado para verificação de status.

. Use o seguinte URI para verificar o status:
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
. Quando o trabalho estiver concluído, valide o relatório de migração. Você pode ver o relatório da resposta do trabalho como parte do jobData.
. Adicione o fornecedor de armazenamento de ferramentas ONTAP 10,0 ao vCenter e link:../configure/register_vasa.html["Registre o provedor VASA no vCenter"]ao .
. Interrompa o serviço do fornecedor de armazenamento de ferramentas ONTAP 9,10 /9,11 Vasa Provider (INTERROMPA o fornecedor Vasa do console de manutenção).
+
A NetApp recomenda que você não exclua o provedor VASA.

+
Depois que o antigo provedor VASA é interrompido, o vCenter faz failover para as ferramentas do ONTAP para VMware vSphere 10,0. Todos os armazenamentos de dados e VMs ficam acessíveis e são fornecidos a partir das ferramentas do ONTAP para VMware vSphere 10,0.

. Execute a migração de patch usando a seguinte API:
+
[listing]
----
/virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
+
O corpo da solicitação está vazio para operação de patch.

+

NOTE: uuid é a migração uuid retornada na resposta da API pós migração.

+
Uma vez que a API de migração de patch for bem-sucedida, todas as VMs estarão em conformidade com a política de armazenamento.



A API de exclusão para migração é:

[listing]
----
Delete /virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
Esta API exclui a migração por ID de migração e exclui a migração no vCenter fornecido.

Após a migração bem-sucedida e depois de Registrar as ferramentas do ONTAP 10,0 no vCenter, faça o seguinte:

* Atualize o certificado em todos os hosts.
* Aguarde algum tempo antes de executar operações de datastore (DS) e Virtual Machine (VM). O tempo de espera depende do número de hosts, DS e VMs que estão presentes na configuração. Quando você não espera, as operações podem falhar intermitentemente.

