---
permalink: deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Antes de implantar as ferramentas do ONTAP para o VMware vSphere, você deve estar familiarizado com os requisitos de espaço para o pacote de implantação e alguns requisitos básicos do sistema de host. 
---
= Requisitos para implantar as ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implantar as ferramentas do ONTAP para o VMware vSphere, você deve estar familiarizado com os requisitos de espaço para o pacote de implantação e alguns requisitos básicos do sistema de host.

Você pode usar as ferramentas do ONTAP com um Windows vCenter Server ou com um vCSA (VMware vCenter Server Virtual Appliance). Você deve implantar as ferramentas do ONTAP em um vSphere compatível que inclua o sistema ESXi.

* * Requisitos de espaço do pacote de instalação por nó*
+
** 10 GB para instalações com provisionamento reduzido
** 200 GB para instalações com provisionamento espesso


* *Requisitos de dimensionamento do sistema anfitrião por nó* a memória recomendada de acordo com o tamanho da implementação e por nó é como mostrado na tabela abaixo:


|===


| Tipo de implantação | CPUs | Memória (GB) 


| Pequeno (S) | 8 | 16 


| Médio (M) | 12 | 24 


| Grande (L) | 16 | 32 
|===


== Requisitos mínimos de storage e aplicação:

|===
| Storage, host e aplicações | Requisitos de versão 


| ONTAP | ONTAP 9.10,1 , 9,11 , 9,12 e 9,13 


| VMware vSphere | A versão mínima suportada do VMware é 7,0.3. 


| Hosts ESXi | ESXi 7.0.3 ou versão posterior 


| Servidor vCenter | VCenter 7.0.3 


| Fornecedor VASA | 3,0 


| Aplicação OVA | 10,0 
|===
A ferramenta de Matriz de interoperabilidade (IMT) contém as informações mais recentes sobre as versões suportadas do ONTAP, vCenter Server, hosts ESXi e aplicativos de plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade"^]



== Considerações adicionais de implantação

Você deve considerar poucos requisitos ao personalizar as ferramentas do ONTAP de implantação.



=== Senha do usuário do aplicativo

Esta é a palavra-passe atribuída à conta de administrador. Por razões de segurança, recomenda-se que o comprimento da senha tenha de oito a trinta carateres e contenha um mínimo de um caractere superior, um inferior, um dígito e um especial. A senha expira após 90 dias.



=== Credenciais do console de manutenção do dispositivo

Você deve acessar o console de manutenção usando o nome de usuário "mal". Você pode definir a senha para o usuário "não" durante a implantação. Você pode usar o menu Configuração do aplicativo do console de manutenção das ferramentas do ONTAP para alterar a senha.



=== Endereço IP do vCenter Server

* Você deve fornecer o endereço IP (IPv4) da instância do vCenter Server à qual deseja Registrar as ferramentas do ONTAP.
+
O tipo de ferramentas ONTAP e certificados VASA gerados depende do endereço IP (IPv4) que você forneceu durante a implantação.

* O endereço IP das ferramentas do ONTAP usado para se Registrar no vCenter Server depende do tipo de endereço IP do vCenter Server (IPv4) inserido no assistente de implantação.
+
As ferramentas ONTAP e os certificados VASA serão gerados usando o mesmo tipo de endereço IP usado durante o Registro do vCenter Server.

* Certifique-se de que as VMs não sejam migradas durante a instalação.
+

NOTE: O IPv6 não é compatível com as ferramentas do ONTAP para a versão do VMware vSphere 10,0.





=== Propriedades da rede do dispositivo

Especifique um nome de host DNS válido (não qualificado), bem como o endereço IP estático para as ferramentas ONTAP e os outros parâmetros de rede. O DHCP não é suportado nas ferramentas do ONTAP para a versão do VMware vSphere 10,0. Todos esses parâmetros são necessários para a instalação e operação adequadas.
