---
permalink: concepts/asup.html 
sidebar: sidebar 
keywords:  
summary: O AutoSupport é um mecanismo que monitora proativamente a integridade do sistema e envia mensagens automaticamente para o suporte técnico da NetApp, sua organização de suporte interno e um parceiro de suporte. Embora as mensagens do AutoSupport para suporte técnico estejam habilitadas por padrão, você deve definir as opções corretas e ter um host de e-mail válido para que as mensagens sejam enviadas para sua organização interna de suporte. 
---
= AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O AutoSupport é um mecanismo que monitora proativamente a integridade do sistema e envia mensagens automaticamente para o suporte técnico da NetApp, sua organização de suporte interno e um parceiro de suporte.

O AutoSupport é ativado por padrão quando você configura o sistema de storage pela primeira vez. O AutoSupport começa a enviar mensagens para o suporte técnico 24 horas após a ativação do AutoSupport.

Você pode ativar ou desativar o AutoSupport somente no momento da implantação. Recomenda-se que o deixe ativado. A ativação do AutoSupport pode ajudar a acelerar significativamente a determinação e a resolução de problemas em caso de problema no sistema de storage. Por padrão, o sistema coleta informações do AutoSupport e as armazena localmente, mesmo que você desative o AutoSupport. Você precisa colocar a lista de permissões 216.240.21.18 // support.NetApp.com URL na sua rede para uma transmissão bem-sucedida.
