---
permalink: concepts/concept_ontap_tools_overview.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere gerenciam o provisionamento de datastores e máquinas virtuais em ambientes VMware que usam backends de storage do NetApp. 
---
= Visão geral das ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para VMware vSphere gerenciam o provisionamento de datastores e máquinas virtuais em ambientes VMware que usam backends de storage do NetApp. Ele permite que os administradores gerenciem o storage no vCenter Server diretamente, simplificando o storage e o gerenciamento de dados para ambientes VMware.

As ferramentas do ONTAP para o VMware vSphere 10,0 são uma coleção de microsserviços horizontalmente escaláveis, orientados a eventos, implantados como um dispositivo virtual aberto (OVA). Ele é empacotado em vários fatores de forma de implantação, como Open Virtual Appliance (OVA) e Software as a Service (SaaS) para on-premise.

As ferramentas do ONTAP para VMware vSphere consistem em:

* Funcionalidade da máquina virtual
* FORNECEDOR VASA para VM granular
* Gerenciamento baseado em política de storage




== ONTAP Tools Fornecedor VASA

O fornecedor VASA suporta requisitos de alta escala para volumes virtuais (vVols) ONTAP. Ele dá suporte ao protocolo NFS, ao protocolo iSCSI e à implantação DE OVA. O VASA Provider para VMware é um produto que fornece gerenciamento de ciclo de vida em uma implantação da VMware com o ONTAP.
