---
permalink: concepts/concept_configure_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Você pode usar o provedor VASA para ONTAP para criar e gerenciar volumes virtuais VMware (vVols). Você pode provisionar, editar, montar e excluir um datastore vVols. Você também pode adicionar storage ao datastore vVols ou remover o storage do datastore vVols para fornecer maior flexibilidade.' 
---
= Configurações do provedor VASA para vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o provedor VASA para ONTAP para criar e gerenciar volumes virtuais VMware (vVols). Você pode provisionar, editar, montar e excluir um datastore vVols. Você também pode adicionar storage ao datastore vVols ou remover o storage do datastore vVols para fornecer maior flexibilidade.

Um datastore vVols consiste em um ou mais volumes FlexVol em um contêiner de storage (também chamado de armazenamento de backup). Uma máquina virtual pode ser espalhada por um datastore vVols ou vários datastores vVols.

Embora você possa criar um armazenamento de dados vVols que tenha vários volumes FlexVol, todos os volumes FlexVol no contêiner de storage devem usar o mesmo protocolo (NFS ou iSCSI) e as mesmas máquinas virtuais de storage (SVMs).


NOTE: É uma boa prática incluir vários volumes FlexVol em um armazenamento de dados vVols para obter desempenho e flexibilidade. Como os volumes do FlexVol têm restrições de contagem de LUN que limitam o número de máquinas virtuais, incluindo vários volumes do FlexVol, você pode armazenar mais máquinas virtuais no armazenamento de dados do vVols. A adição de diversos volumes aumenta as capacidades do datastore, onde pode haver uma combinação de volumes finos e espessos para que ambos os tipos de VMs possam ser criados no datastore.

O VASA Provider cria diferentes tipos de vVols durante o provisionamento de máquina virtual ou a criação do VMDK.

* *Config*
+
O VMware vSphere usa esse datastore vVols para armazenar informações de configuração.

+
Em implementações de SAN (bloco), o armazenamento é um LUN de 4 GB. O vCenter 8 leva a capacidade para 256GB LUN em thin Provisioning.

+
Em uma implementação NFS, este é um diretório contendo arquivos de configuração da VM, como o arquivo vmx e ponteiros para outros datastores vVols.

* *Dados*
+
Este vVols contém informações do sistema operacional e arquivos de usuário.

+
Em implementações SAN, este é um LUN que é o tamanho do disco virtual.

+
Em uma implementação NFS, este é um arquivo que é o tamanho do disco virtual.

* *Troca*
+
Este vVols é criado quando a máquina virtual é ligada e é excluído quando a máquina virtual é desligada.

+
Em implementações SAN, este é um LUN que é o tamanho da memória virtual.

+
Em uma implementação NFS, este é um arquivo que é o tamanho da memória virtual.

* *Memória*
+
Este vVols é criado se a opção instantâneos de memória estiver selecionada ao criar snapshot de VM.

+
Em implementações SAN, este é um LUN que é o tamanho da memória virtual.

+
Em uma implementação NFS, este é um arquivo que é o tamanho da memória virtual.


