---
permalink: configure/associate_storage_backend.html 
sidebar: sidebar 
keywords:  
summary: precisa de informações. 
---
= Associar o back-end de storage ao vCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página de listagem do vCenter mostra o número associado de backends de armazenamento. Cada vCenter tem a opção de associar um back-end de storage

*Sobre esta tarefa*

Essa tarefa ajuda você a criar um mapeamento entre o back-end de storage e o vCenter integrado globalmente.

*Passos*

. Inicie `\https://loadBalanceIP:8443/virtualization/ui/` a partir do navegador com as credenciais de administrador das ferramentas do ONTAP fornecidas durante a implantação.
. Selecione vCenters na barra lateral.
. Clique na elipse vertical em relação ao vCenter que você deseja associar aos backends de armazenamento.
. Selecione back-end de armazenamento no menu suspenso na janela pop-up.
. Selecione a opção *Associate Storage backend* para associar o vCenter ao back-end de armazenamento necessário.
+
link:../configure/task_configure_user_role_and_privileges.html["Lista de Privileges mínimo necessário para usuário de cluster com escopo global não administrador"]Consulte .


