---
permalink: manage/task_mount_a_vvols_datastore.html 
sidebar: sidebar 
keywords: Mount vVol 
summary: 'Você pode montar um datastore do VMware Virtual volumes (vVols) em um ou mais hosts adicionais usando a caixa de diálogo armazenamento de dados do Mount vVols. A montagem do datastore fornece acesso ao storage a hosts adicionais. Você também pode desmontar o vVols datastore.' 
---
= Montar e desmontar um datastore vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível montar um armazenamento de dados do VMware Virtual volumes (vVols) em um ou mais hosts adicionais usando a caixa de diálogo armazenamento de dados do Mount vVols. A montagem do datastore fornece acesso ao storage a hosts adicionais. Você também pode desmontar o vVols datastore.

Use a seguinte API para montar ou desmontar um datastore vVols. Você precisa passar o x-auth para a API. Você pode gerar esse x-auth a partir da nova API adicionada em Auth no Swagger.

[listing]
----
/virtualization/api/v1/auth/vcenter-login
----
[listing]
----
PATCH
/virtualization/api/v1/vcenters/{vcguid}/vvols/datastores/{moref}/hosts
----
Obtenha o moref do vVol datastore do vCenter.

Solicitar corpo

[listing]
----
{
  "operation": "mount",
  "morefs": [
    "host-7044"
  ],
}
----


== Exemplos:

* Monte em host adicional


Use a seguinte API para montar em host adicional:

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "mount",
      "morefs": ["host-13"],
     }
----
* Desmontar em host adicional


Use a seguinte API para desmontar em host adicional:

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "unmount",
      "morefs": ["host-13"],
     }
----