---
permalink: manage/update_vcenter_ontap_credentials.html 
sidebar: sidebar 
keywords:  
summary: Você pode atualizar as credenciais do vCenter e do ONTAP usando o console de manutenção. 
---
= Atualize as credenciais do vCenter e do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar as credenciais do vCenter e do ONTAP usando o console de manutenção.

*O que você vai precisar*

Você precisa ter credenciais de login de usuário de manutenção.

*Sobre esta tarefa*

Se você tiver alterado as credenciais para a implantação pós-vCenter, ONTAP ou Datalif, precisará atualizar as credenciais usando este procedimento.

*Passos*

. No vCenter Server, abra um console para o provedor VASA.
. Inicie sessão como utilizador de manutenção.
. Entre `4` para selecionar suporte e Diagnóstico.
. Introduza `1` para selecionar Access diagnostic shell (Acesso à shell de diagnóstico).
. Entre `y` para continuar.
. Atualize as credenciais conforme necessário:
+
.. Para atualizar as credenciais do ONTAP, execute o comando:
+
--
otv-update --ontapUsername <new username> --ontapPassword <new password>

--
.. Para atualizar as credenciais do vCenter, execute o comando:
+
--
otv-update --vcenterUsername <new username> --vcenterPassword <new password>

--
.. Para atualizar o datalif execute o comando:
+
--
otv-update --dataLif (novo IP de Datalif>)

--



